### PR TITLE
Expect failure, retry

### LINKED ISSUE #15: flake: Failed on validate-public at the end of a run
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/453/consoleFull

```
TASK [openshift-registry : Wait for registry to be running] ********************
Friday 10 February 2017  19:05:13 +0000 (0:00:00.567)       0:13:59.997 ******* 
FAILED - RETRYING: TASK: openshift-registry : Wait for registry to be running (30 retries left).
changed: [ci-prtest453-ig-m-bs5c]

TASK [openshift-roles : Assign roles to cluster users] *************************
Friday 10 February 2017  19:05:44 +0000 (0:00:31.207)       0:14:31.205 ******* 

PLAY [localhost] ***************************************************************

TASK [validate-public : Validate the public address] ***************************
Friday 10 February 2017  19:05:44 +0000 (0:00:00.023)       0:14:31.229 ******* 
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: An unknown error occurred: ''", "redirected": false, "status": -1, "url": "https://api.prtest453.origin-ci-int-gce.dev.rhcloud.com:443/healthz/ready"}

PLAY RECAP *********************************************************************
ci-prtest453-ig-m-bs5c     : ok=561  changed=188  unreachable=0    failed=0   
ci-prtest453-ig-n-31n1     : ok=183  changed=69   unreachable=0    failed=0   
ci-prtest453-ig-n-d0jp     : ok=183  changed=69   unreachable=0    failed=0   
ci-prtest453-ig-n-g910     : ok=183  changed=69   unreachable=0    failed=0   
localhost                  : ok=22   changed=7    unreachable=0    failed=1   

Friday 10 February 2017  19:05:49 +0000 (0:00:04.981)       0:14:36.211 ******* 
```

We should be ready at this point, maybe the load balancer was wrong?  We should retry and maybe debug more info.

### PR DESCRIPTION
**Pull request by sdodson**
Maybe fixes #15

### CODE REVIEW

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
@smarterclayton PTAL

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test

**Comment by smarterclayton** [comment]
[test]

**Pull request merged**
